# Workflow for manual test of feed generation (testing only)
name: Test Feed Generation

# Trigger: manual only (no schedule)
on:
  workflow_dispatch: # Only runs when triggered manually

jobs:
  test-feed:
    # This job is for testing purposes only
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python 3.11 environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # Ensure compatibility with dependencies

      # Install required system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y python3-setuptools

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run test_blog.py only, outputting to feed_test.xml
      - name: Run test_blog.py and output to feed_test.xml
        run: |
          set -e  # Fail the step on any error
          source venv/bin/activate
          python feed_generators/test_blog.py --output feed_test.xml

      # (Optional) Upload the test output as an artifact for inspection
      - name: Upload feed_test.xml artifact
        uses: actions/upload-artifact@v2
        with:
          name: feed_test.xml
          path: feed_test.xml
# Notes:
# - This workflow is intended for testing only and will not run automatically.
# - It executes only test_blog.py and outputs to feed_test.xml.
# - Use workflow_dispatch to trigger manually from the Actions tab.
